### ISSUE TITLE
consegna incompleta

### ISSUE THREAD

**Issue by fulcorno** [TdP-prove-finali/ManzettiFederico#1]
Il progetto non può essere valutato in quanto manca la relazione PDF ed il link al video di presentazione.

**Comment by FedericoManzetti** [comment]
Avevo erroneamente caricato la relazione solo sul disco condiviso, ora il progetto è stato aggiornato con le relazioni ed il link al video dimostrativo. Grazie e chiedo scusa per il contrattempo.
